import { Course, Enrollment } from './types';

export const categories = [
  'Mathematics', 'Science', 'English', 'Computer Science', 'Business', 'Arts', 'Languages'
];

export const mockCourses: Course[] = [
  {
    id: '1',
    title: 'Mathematics O-Level Complete Course',
    description: 'Master O-Level Mathematics with comprehensive lessons covering algebra, geometry, trigonometry, statistics, and more. This course is designed to build strong foundations and prepare students for exams with practice problems and step-by-step solutions.',
    shortDescription: 'Complete O-Level Mathematics preparation with practice problems and exam strategies.',
    price: 49.99,
    originalPrice: 79.99,
    image: '',
    category: 'Mathematics',
    level: 'Intermediate',
    duration: '40 hours',
    lessons: 120,
    students: 2340,
    rating: 4.8,
    reviewCount: 312,
    instructor: 'Dr. Sarah Ahmed',
    instructorAvatar: '',
    featured: true,
    moodleCourseId: 5,
    curriculum: [
      { title: 'Number Systems & Operations', lessons: [{ title: 'Introduction to Number Types', duration: '15 min', free: true }, { title: 'Operations with Integers', duration: '20 min' }, { title: 'Fractions and Decimals', duration: '25 min' }] },
      { title: 'Algebra Fundamentals', lessons: [{ title: 'Variables and Expressions', duration: '18 min' }, { title: 'Linear Equations', duration: '22 min' }, { title: 'Quadratic Equations', duration: '30 min' }] },
      { title: 'Geometry', lessons: [{ title: 'Angles and Lines', duration: '20 min' }, { title: 'Triangles and Circles', duration: '25 min' }] },
    ],
    requirements: ['Basic arithmetic knowledge', 'Notebook and calculator'],
    outcomes: ['Solve complex algebraic equations', 'Master geometric proofs', 'Score high on O-Level exams'],
  },
  {
    id: '2',
    title: 'Physics A-Level Masterclass',
    description: 'Dive deep into A-Level Physics with engaging video lessons, lab simulations, and exam preparation materials. Cover mechanics, waves, electricity, and modern physics.',
    shortDescription: 'Advanced Physics preparation with lab simulations and exam practice.',
    price: 69.99,
    originalPrice: 99.99,
    image: '',
    category: 'Science',
    level: 'Advanced',
    duration: '55 hours',
    lessons: 160,
    students: 1850,
    rating: 4.7,
    reviewCount: 248,
    instructor: 'Prof. James Okafor',
    instructorAvatar: '',
    featured: true,
    moodleCourseId: 6,
    curriculum: [
      { title: 'Mechanics', lessons: [{ title: 'Kinematics', duration: '20 min', free: true }, { title: 'Forces and Motion', duration: '25 min' }] },
      { title: 'Waves & Optics', lessons: [{ title: 'Wave Properties', duration: '22 min' }, { title: 'Light and Refraction', duration: '28 min' }] },
    ],
    requirements: ['O-Level Physics or equivalent', 'Scientific calculator'],
    outcomes: ['Understand core physics principles', 'Solve advanced mechanics problems', 'Prepare for A-Level exams'],
  },
  {
    id: '3',
    title: 'English Literature & Composition',
    description: 'Enhance your English skills with comprehensive lessons on literature analysis, essay writing, creative writing, and critical thinking. Perfect for students preparing for language exams.',
    shortDescription: 'Master English literature analysis and composition skills.',
    price: 39.99,
    image: '',
    category: 'English',
    level: 'Beginner',
    duration: '30 hours',
    lessons: 85,
    students: 3120,
    rating: 4.9,
    reviewCount: 420,
    instructor: 'Ms. Emily Chen',
    instructorAvatar: '',
    featured: true,
    moodleCourseId: 7,
    curriculum: [
      { title: 'Essay Writing', lessons: [{ title: 'Essay Structure', duration: '15 min', free: true }, { title: 'Thesis Development', duration: '20 min' }] },
      { title: 'Literature Analysis', lessons: [{ title: 'Poetry Analysis', duration: '25 min' }, { title: 'Prose Analysis', duration: '22 min' }] },
    ],
    requirements: ['Basic English reading and writing ability'],
    outcomes: ['Write compelling essays', 'Analyze literary works', 'Improve critical thinking'],
  },
  {
    id: '4',
    title: 'Introduction to Computer Science',
    description: 'Learn programming fundamentals, algorithms, data structures, and web development basics. Build real projects and develop computational thinking skills.',
    shortDescription: 'Programming fundamentals with hands-on projects.',
    price: 59.99,
    originalPrice: 89.99,
    image: '',
    category: 'Computer Science',
    level: 'Beginner',
    duration: '45 hours',
    lessons: 130,
    students: 4500,
    rating: 4.6,
    reviewCount: 560,
    instructor: 'David Kimani',
    instructorAvatar: '',
    moodleCourseId: 8,
    curriculum: [
      { title: 'Programming Basics', lessons: [{ title: 'What is Programming?', duration: '12 min', free: true }, { title: 'Variables and Data Types', duration: '18 min' }] },
      { title: 'Web Development', lessons: [{ title: 'HTML & CSS Basics', duration: '25 min' }, { title: 'JavaScript Introduction', duration: '30 min' }] },
    ],
    requirements: ['No prior programming experience needed', 'A computer with internet access'],
    outcomes: ['Write basic programs', 'Build simple websites', 'Understand algorithms'],
  },
  {
    id: '5',
    title: 'Business Studies & Entrepreneurship',
    description: 'Explore business concepts, marketing strategies, financial management, and entrepreneurship. Learn to create business plans and understand market dynamics.',
    shortDescription: 'Business fundamentals and entrepreneurship skills.',
    price: 44.99,
    image: '',
    category: 'Business',
    level: 'Intermediate',
    duration: '35 hours',
    lessons: 95,
    students: 1200,
    rating: 4.5,
    reviewCount: 180,
    instructor: 'Maria Santos',
    instructorAvatar: '',
    moodleCourseId: 9,
    curriculum: [
      { title: 'Business Fundamentals', lessons: [{ title: 'Introduction to Business', duration: '15 min', free: true }, { title: 'Market Research', duration: '20 min' }] },
    ],
    requirements: ['Interest in business and entrepreneurship'],
    outcomes: ['Create a business plan', 'Understand financial statements', 'Develop marketing strategies'],
  },
  {
    id: '6',
    title: 'Chemistry O-Level Foundations',
    description: 'Build a solid foundation in Chemistry with interactive lessons on atomic structure, chemical bonding, reactions, and organic chemistry basics.',
    shortDescription: 'O-Level Chemistry with interactive experiments.',
    price: 44.99,
    originalPrice: 64.99,
    image: '',
    category: 'Science',
    level: 'Intermediate',
    duration: '38 hours',
    lessons: 110,
    students: 1980,
    rating: 4.7,
    reviewCount: 290,
    instructor: 'Dr. Amina Hassan',
    instructorAvatar: '',
    moodleCourseId: 10,
    curriculum: [
      { title: 'Atomic Structure', lessons: [{ title: 'Atoms and Elements', duration: '18 min', free: true }, { title: 'Electronic Configuration', duration: '22 min' }] },
    ],
    requirements: ['Basic science knowledge'],
    outcomes: ['Understand chemical reactions', 'Balance chemical equations', 'Prepare for O-Level exams'],
  },
];

export const mockEnrollments: Enrollment[] = [
  {
    id: 'e1',
    course: mockCourses[0],
    progress: 65,
    enrolledAt: '2025-11-15',
    status: 'active',
    lastAccessed: '2026-02-11',
  },
  {
    id: 'e2',
    course: mockCourses[2],
    progress: 100,
    enrolledAt: '2025-09-01',
    status: 'completed',
    lastAccessed: '2025-12-20',
  },
  {
    id: 'e3',
    course: mockCourses[3],
    progress: 30,
    enrolledAt: '2026-01-10',
    status: 'active',
    lastAccessed: '2026-02-10',
  },
];

export const mockUser = {
  id: 'u1',
  name: 'Alex Johnson',
  email: 'alex@example.com',
  role: 'student' as const,
  moodleUserId: 42,
};
